name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: abhigyan-709
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg

      - name: Commit and Push Snake
        run: |
          mv dist/snake.svg output/github-contribution-grid-snake.svg
          git config --local user.email "abhigkumar709@gmail.com"
          git config --local user.name "abhigyan-709"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Updated GitHub contribution snake"
          git push
