name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"    # daily at 00:00 UTC
  workflow_dispatch:       # manual run

permissions:
  contents: write

concurrency:
  group: snake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme:
          - { name: "light",  snake: "#FF5733", dots: "#FFD700,#FF6347,#FF4500,#8B0000,#FF1493", extra: "" }
          - { name: "dark",   snake: "#32CD32", dots: "#00FF00,#228B22,#006400,#8B4513,#006400", extra: "palette=github-dark" }
          - { name: "ocean",  snake: "#00BFFF", dots: "#00FFFF,#1E90FF,#4169E1,#191970,#7FFFD4", extra: "" }
          - { name: "neon",   snake: "#39FF14", dots: "#39FF14,#FFD700,#FF00FF,#00FFFF,#FF4500", extra: "" }

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Generate (SVG + GIF)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/${{ matrix.theme.name }}.svg?${{ matrix.theme.extra }}&color_snake=${{ matrix.theme.snake }}&color_dots=${{ matrix.theme.dots }}
            dist/${{ matrix.theme.name }}.gif?${{ matrix.theme.extra }}&color_snake=${{ matrix.theme.snake }}&color_dots=${{ matrix.theme.dots }}

      - name: Upload artifacts for ${{ matrix.theme.name }}
        uses: actions/upload-artifact@v4
        with:
          name: snake-${{ matrix.theme.name }}
          path: |
            dist/${{ matrix.theme.name }}.svg
            dist/${{ matrix.theme.name }}.gif

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: snake-*
          path: artifacts
          merge-multiple: true

      - name: Stage to /output
        run: |
          mkdir -p output
          for f in artifacts/*.svg; do
            base=$(basename "$f" .svg)
            cp "$f" "output/github-contribution-snake-${base#light}.svg" 2>/dev/null || true
            cp "$f" "output/github-contribution-snake-${base}.svg" 2>/dev/null || true
          done
          for f in artifacts/*.gif; do
            base=$(basename "$f" .gif)
            cp "$f" "output/github-contribution-snake-${base#light}.gif" 2>/dev/null || true
            cp "$f" "output/github-contribution-snake-${base}.gif" 2>/dev/null || true
          done

      - name: Commit changes (single commit) with [skip ci]
        run: |
          git config --local user.email "abhigkumar709@gmail.com"
          git config --local user.name  "abhigyan-709"
          git add output/
          git diff --cached --quiet || git commit -m "chore: update snake assets [skip ci]"

      - name: Push
        run: |
          git pull --rebase origin main || true
          git push origin HEAD:main || true
