name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare Output Directory
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: abhigyan-709

      - name: Debug Workspace
        run: |
          echo "Workspace contents:"
          ls -la
          echo "Contents of dist/:"
          ls -la dist

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg

      - name: Commit and Push Snake
        run: |
          mkdir -p output
          mv dist/snake.svg output/github-contribution-grid-snake.svg
          git config --local user.email "abhigkumar709@gmail.com"
          git config --local user.name "abhigyan-709"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Updated GitHub contribution snake"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git push
